CodePad/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from codepadapp import views, codepadadmin, students, faculty, exam
import codepadapp

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^index',views.index, name='index'),
    url(r'^contact',views.contact, name='contact'),

    url(r'^about', views.about, name='about'),
    url(r'^gallery', views.gallery, name='gallery'),
    url(r'^index', views.home, name="home") ,
    url(r'^Admin/home', codepadadmin.index, name='admin'),
    url(r'^Admin/lab', codepadadmin.lab, name='lab'),
    url(r'^Admin/Faculty', codepadadmin.faculty, name='Faculty'),
    url(r'^Admin/logout', codepadadmin.logout, name='logout'),
    url(r'^Admin/exam',codepadadmin.exam,name='exam'),
    url(r'^Admin/contact',codepadadmin.contact,name='contact'),
    #url(r'^Admin/Faculty', codepadadmin.faculties, name='Faculties'),
    url(r'^Admin/editfaculty/(?P<id>\w+)/', codepadadmin.edit_Faculty, name='editfacultys'),
    url(r'^Admin/deletefaculty/(?P<id>\w+)/', codepadadmin.delete_Faculty, name='deletefacultys'),

    url(r'^Student/home', students.index, name='student'),
    url(r'^Student/lab', students.lab, name='lab'),
    url(r'^Student/runprogram/(?P<lab>\w+)/', students.runprogram, name='runprogram'),
    url(r'^Student/exec', students.execprogram, name='exec'),
    url(r'^Student/downloadprogram/(?P<name>\w+)/(?P<program>\w+)/', students.downloadprogram, name='download'),
    url(r'^Student/saveprogram', students.save_program, name='save'),
    url(r'^Student/getsavedprograms', students.get_saved_programs, name='savedprograms'),
    url(r'Student/exam',students.exam, name='exam'),
    url(r'Student/contact',students.contact, name='contact'),
    url(r'^Student/logout', students.logout, name='logout'),

    url(r'^Faculty/home', faculty.index, name='faculty'),
    url(r'^Faculty/lab', faculty.lab, name='lab'),
    url(r'^Faculty/liststudents/(?P<lab>\w+)/', faculty.list_students, name='labstudents'),
    url(r'^Faculty/runprogram/(?P<lab>\w+)/', faculty.runprogram, name='runprogram'),
    url(r'^Faculty/students', faculty.students, name='students'),url(r'^Faculty/home', faculty.index, name='faculty'),
    url(r'^Faculty/newstudent', faculty.new_student, name='newstudents'),
    url(r'^Faculty/editstudent/(?P<id>\w+)/', faculty.edit_student, name='editstudents'),
    url(r'^Faculty/deletestudent/(?P<id>\w+)/', faculty.delete_student, name='deletestudents'),
    url(r'^Faculty/contact',faculty.contact, name='contact'),
    url(r'^Faculty/exam',faculty.exam, name='exam'),
    url(r'^Faculty/addexam',faculty.addexam, name='addexam'),
    url(r'^Faculty/lexamstudents/(?P<examid>\w+)/', faculty.examstudents, name='examstudents'),
    url(r'^Faculty/eanswers/(?P<answerid>\w+)/', faculty.examanswer, name='examanswers'),
    url(r'^Faculty/logout', faculty.logout, name='logout'),

    url(r'^Exam/home', exam.index, name='exam'),
    url(r'^Exam/exam', exam.exam, name='exams'),
    url(r'^Exam/labexam/(?P<examid>\w+)/', exam.labexam, name='labexam'),
    url(r'^Exam/saveprogram', exam.save_program, name='save'),
    url(r'^Exam/logout', exam.logout, name='logout'),
]

codepadapp/models.py
from __future__ import unicode_literals
from _ast import mod
from django.db import models


class Login(models.Model):
    username = models.CharField(max_length=256)
    password = models.CharField(max_length=256)
    type = models.CharField(max_length=256)
    status = models.CharField(max_length=256)

    def __str__(self):
        return self.username


class Students(models.Model):
    loginid = models.ForeignKey(Login)
    admission_no = models.CharField(max_length=256)
    firstname = models.CharField(max_length=256)
    lastname = models.CharField(max_length=256)
    address = models.CharField(max_length=1024)
    contact = models.CharField(max_length=256)
    email = models.CharField(max_length=256)
    department = models.CharField(max_length=256)
    semester = models.CharField(max_length=256)

    def __str__(self):
        return self.firstname


class Faculty(models.Model):
    loginid = models.ForeignKey(Login)
    staffid = models.CharField(max_length=256)
    name = models.CharField(max_length=256)
    designation = models.CharField(max_length=256)
    email = models.EmailField()
    phone = models.CharField(max_length=256)

    def __str__(self):
        return self.name


class Lab(models.Model):
    labname = models.CharField(max_length=256)
    semester = models.CharField(max_length=256)
    language = models.CharField(max_length=256)
    faculty = models.ForeignKey(Faculty)

    def __str__(self):
        return self.labname

    def faculty_name(self):
        return self.faculty.name


class UserPrograms(models.Model):
    loginid = models.ForeignKey(Login)
    lab = models.ForeignKey(Lab)
    language = models.CharField(max_length=256)
    programname = models.CharField(max_length=256)
    date = models.DateTimeField()
    path = models.CharField(max_length=256)

    def __str__(self):
        return self.programname


class Exam(models.Model):
    examname = models.CharField(max_length=256)
    date = models.DateField()
    time = models.TimeField()
    lab = models.ForeignKey(Lab)
    semester = models.CharField(max_length=256)

    def __str__(self):
        return self.examname


class ExamQuestions(models.Model):
    question = models.CharField(max_length=1024)
    exam = models.ForeignKey(Exam)

    def __str__(self):
        return self.question


class ExamLogin(models.Model):
    prefix = models.CharField(max_length=256)


class ExamAnswers(models.Model):
    name = models.CharField(max_length=256)
    loginid = models.ForeignKey(Login)
    examquestion = models.ForeignKey(ExamQuestions)
    path = models.CharField(max_length=1024)
    datetime = models.DateTimeField()

    def __str__(self):
        return self.examquestion.question


class ExamMarks(models.Model):
    login = models.ForeignKey(Login)
    examid = models.ForeignKey(Exam)
    mark = models.FloatField()
    total = models.FloatField()
    datetime =models.DateTimeField()

codepadapp/forms.py
from django import forms
from codepadapp.models import Faculty, Lab


class LoginForm(forms.Form):
    username = forms.CharField(max_length=100, label='', widget=forms.TextInput(attrs={'required': 'true', 'placeholder': 'Username', 'class': 'form-control'}))
    password = forms.CharField(max_length=100, label='', widget=forms.PasswordInput(attrs={'required': 'true', 'placeholder': 'Password', 'class': 'form-control'}))


class AddStudentsForm(forms.Form):
    file = forms.FileField(label='Select Student data')


class LabForm(forms.Form):
    semoptions = (('1', 'Sem 1'), ('2', 'Sem 2'), ('3', 'Sem 3'), ('4', 'Sem 4'), ('5', 'Sem 5'), ('6', 'Sem 6'), ('7', 'Sem 7'), ('8', 'Sem 8'))
    languageoptions = (('C', 'C'), ('CPP', 'CPP'), ('Java', 'Java'))

    name = forms.CharField(max_length=100, label='Lab Name', widget=forms.TextInput(attrs={'required': 'true', 'placeholder': 'Lab Name', 'class': 'form-control'}))
    semester = forms.ChoiceField(choices=semoptions, label='Semester', widget=forms.Select(attrs={'required': 'true', 'class': 'form-control'}))
    language = forms.ChoiceField(choices=languageoptions, label='Language', widget=forms.Select(attrs={'required': 'true', 'class': 'form-control'}))
    faculty = forms.ModelChoiceField(queryset=Faculty.objects.all(), label='Faculty', widget=forms.Select(attrs={'required': 'true', 'class': 'form-control'}))


class FacultyForm(forms.Form):
    staffid = forms.CharField(max_length=100, label='', widget=forms.TextInput(attrs={'required': 'true', 'placeholder': 'Staff ID', 'class': 'form-control'}))
    name = forms.CharField(max_length=100, label='', widget=forms.TextInput(attrs={'required': 'true', 'placeholder': 'Name', 'class': 'form-control'}))
    designation = forms.CharField(max_length=100, label='', widget=forms.TextInput(attrs={'required': 'true', 'placeholder': 'Designation', 'class': 'form-control'}))
    email = forms.CharField(max_length=100, label='', widget=forms.EmailInput(attrs={'required': 'true', 'placeholder': 'Email', 'class': 'form-control'}))
    phone = forms.CharField(max_length=100, label='', widget=forms.TextInput(attrs={'required': 'true', 'placeholder': 'Phone', 'class': 'form-control'}))


class NewStudentForm(forms.Form):
    admission_no = forms.CharField(max_length=100, label='', widget=forms.TextInput(attrs={'required': 'true', 'placeholder': 'Admission No', 'class': 'form-control'}))
    firstname = forms.CharField(max_length=100, label='', widget=forms.TextInput(attrs={'required': 'true', 'placeholder': 'First Name', 'class': 'form-control'}))
    lastname = forms.CharField(max_length=100, label='', widget=forms.TextInput(attrs={'required': 'true', 'placeholder': 'Last Name', 'class': 'form-control'}))
    address = forms.CharField(max_length=100, label='', widget=forms.Textarea(attrs={'required': 'true', 'placeholder': 'Address', 'class': 'form-control'}))
    contact = forms.CharField(max_length=100, label='', widget=forms.TextInput(attrs={'required': 'true', 'placeholder': 'Phone', 'class': 'form-control'}))
    email = forms.CharField(max_length=100, label='', widget=forms.EmailInput(attrs={'required': 'true', 'placeholder': 'Email', 'class': 'form-control'}))
    department = forms.CharField(max_length=100, label='', widget=forms.TextInput(attrs={'required': 'true', 'placeholder': 'Department', 'class': 'form-control'}))
    semester = forms.CharField(max_length=100, label='', widget=forms.TextInput(attrs={'required': 'true', 'placeholder': 'Semester', 'class': 'form-control'}))


class ChangePasswordForm(forms.Form):
    currentpassword = forms.CharField(max_length=100, label='', widget=forms.PasswordInput(attrs={'required': 'true', 'placeholder': 'Current Password', 'class': 'form-control'}))
    newpassword = forms.CharField(max_length=100, label='', widget=forms.PasswordInput(attrs={'required': 'true', 'placeholder': 'New Password', 'class': 'form-control'}))
    confirmpassword = forms.CharField(max_length=100, label='', widget=forms.PasswordInput(attrs={'required': 'true', 'placeholder': 'Confirm Password', 'class': 'form-control'}))


class ExamForm(forms.Form):
    name = forms.CharField(max_length=100, label='Exam Name', widget=forms.TextInput(attrs={'required': 'true', 'placeholder': 'Exam Name', 'class': 'form-control'}))
    date = forms.DateField(label="Date", widget=forms.DateInput(attrs={'required': 'true', 'placeholder': 'Date', 'class': 'form-control'}))
    time = forms.TimeField(label="Time", widget=forms.TimeInput(attrs={'required': 'true', 'placeholder': 'Time', 'class': 'form-control'}))
    lab = forms.ModelChoiceField(queryset=Lab.objects.all(), label='Lab', widget=forms.Select(attrs={'required': 'true', 'class': 'form-control'}))
    # semester = forms.CharField(max_length=100, label='Semester', widget=forms.TextInput(attrs={'required': 'true', 'placeholder': 'Semester', 'class': 'form-control'}))
    question1 = forms.CharField(max_length=100, label='Question 1', widget=forms.TextInput(attrs={'required': 'true', 'placeholder': 'Question 1', 'class': 'form-control'}))
    question2 = forms.CharField(max_length=100, label='Question 2', widget=forms.TextInput(attrs={'required': 'true', 'placeholder': 'Question 2', 'class': 'form-control'}))
    question3 = forms.CharField(max_length=100, label='Question 3', widget=forms.TextInput(attrs={'required': 'true', 'placeholder': 'Question 3', 'class': 'form-control'}))
    question4 = forms.CharField(max_length=100, label='Question 4', widget=forms.TextInput(attrs={'required': 'true', 'placeholder': 'Question 4', 'class': 'form-control'}))
    question5 = forms.CharField(max_length=100, label='Question 5', widget=forms.TextInput(attrs={'required': 'true', 'placeholder': 'Question 5', 'class': 'form-control'}))


class ExamMarksForm(forms.Form):
    mark = forms.CharField(max_length=100, label='', widget=forms.TextInput(attrs={'required': 'true', 'placeholder': 'Marks', 'class': 'form-control'}))
    total = forms.CharField(max_length=100, label='', widget=forms.TextInput(attrs={'required': 'true', 'placeholder': 'Out of', 'class': 'form-control'}))

codepadapp/views.py
from django.http.response import HttpResponseRedirect
from django.shortcuts import render, render_to_response, redirect

from codepadapp.forms import LoginForm
from codepadapp.models import Login, Faculty, Students


def about(request):

    return render(request, 'about.html')

def gallery(request):
    return render(request, 'gallery.html')
def home(request):
    return render(request, 'index.html')
def contact(request):
    return render(request,'contact.html')

def index(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            login = Login.objects.filter(username=username, password=password)
            if len(login) > 0:
                if login[0].type == 'admin':
                    return HttpResponseRedirect('/Admin/home')
                elif login[0].type == 'student':
                    name = Students.objects.filter(loginid=login)[0].firstname
                    request.session['id'] = login[0].pk
                    request.session['name'] = name
                    return HttpResponseRedirect('/Student/home')
                elif login[0].type == 'faculty':
                    name = Faculty.objects.filter(loginid=login)[0].name
                    request.session['id'] = login[0].pk
                    request.session['name'] = name
                    return HttpResponseRedirect('/Faculty/home')

            elif username.startswith("exam"):
                request.session['regno'] = username.split("_")[1]
                return HttpResponseRedirect('/Exam/home')

            else:
                request.session['alert'] = 'Invalid Login'

    else:
        request.session['alert'] = None
        form = LoginForm()

    return render(request, 'index.html', {'form': form})

codepadapp/templates/CodepadAdmin/contact.html
<!DOCTYPE HTML>
<html>
<head>
<title>University a Educational Category Flat Bootstrap Responsive Website Template | Home :: w3layouts</title>
    {% load staticfiles %}
<link href="{% static 'css/bootstrap.css'%}" rel='stylesheet' type='text/css' />
<!-- Custom Theme files -->
<link href="{% static 'css/style.css' %}" rel='stylesheet' type='text/css' />
<!-- Custom Theme files -->
<!--//theme-style-->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="University Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<script src="{% static 'js/jquery.min.js' %}"></script>
 <script src="{% static 'js/bootstrap.js' %}"></script>

    <script type="text/javascript">
        $(document).ready(function(){
            $("#loginLink").click(function(e){
                e.preventDefault();
                $("#loginModal").modal();
            });

            {% if request.session.alert != None %}

                $("#alert_info").html("{{ request.session.alert }}");
                $("#alert_model").modal();

            {% endif %}

        });

    function validate(){

{#        if(isNaN($("#id_username").val())){#}
{#            alert("Not number");#}
{#        }#}
        return true;
    }
    </script>

</head>
<body>
<!-- banner -->
<script src="{% static 'js/responsiveslides.min.js' %}"></script>
<script>
    $(function () {
      $("#slider").responsiveSlides({
      	auto: true,
      	nav: true,
      	speed: 500,
        namespace: "callbacks",
        pager: true,
      });
    });
  </script>
<div class="banner">
	 <div class="header">
			 <div class="logo">
				 <a href="index.html"><img src="{% static 'images/logo.jpg' %}" alt=""/></a>
			 </div>
			 <div class="top-menu">
				 <span class="menu"></span>
				 <ul class="navig">
					 <li><a href="/Admin/Home">Home</a></li>
					 <!---<li><a href="index">Home</a></li>-->
					 <!---<li><a href="gallery.html">Gallery</a></li>
					 <li><a href="contact.html">Contact</a></li>
                     <li><a href="" id="loginLink">Login</a></li>--->
				 </ul>
			 </div>
			  <!-- script-for-menu -->
		 <script>
				$("span.menu").click(function(){
					$("ul.navig").slideToggle("slow" , function(){
					});
				});
		 </script>
		 <!-- script-for-menu -->

			 <div class="clearfix"></div>
	 </div>

</div>
<!---->

<!---->
<div class="footer">
	 <div class="container">
		 <div class="ftr-sec">
			 <div class="col-md-4 ftr-grid">
				 <h3>Virtual lab</h3>
				 <p>At the time of learning languages like C, C++, Java Etc. The beginners had number of
problem like to install compilers at desktop-pc. Some time student had to face the problem of
configuring the compiler. So that they can’t get execute the program successfully. And other
problem is that if the users want to compile program on any other system they require again all
processing to install and configuration problem.</p>
				 <p>To solve this problem a python application is
designed to execute the program on different types of source code by one editor. And also a
well configured compiler providing services by servers.Simply to create a common server for
different programming language.To create a common interface for all programming language..</p>
			 </div>
			 <div class="col-md-4 ftr-grid2">
				 <h3>Pages</h3>
				 <ul>
					 <li><a href="index.html"><span></span>Home</a></li>
					 <li><a href="about.html"><span></span>About</a></li>
					 <li><a href="program.html"><span></span>Programs</a></li>
					 <li><a href="blog.html"><span></span>Blog</a></li>
					 <li><a href="gallery.html"><span></span>Gallery</a></li>
					 <li><a href="contact.html"><span></span>Contact</a></li>
				 </ul>
			 </div>
			 <div class="col-md-4 ftr-grid3">
				 <h3>Quick links</h3>
				 <ul>
					 <li><a href="about.html"><span></span>History</a></li>
					 <li><a href="about.html"><span></span>Departments</a></li>
					 <li><a href="gallery.html"><span></span>Services</a></li>
					 <li><a href="blog.html"><span></span>Guidances</a></li>
					 <li><a href="about.html"><span></span>Team</a></li>
					 <li><a href="contact.html"><span></span>Contact</a></li>
				 </ul>
			 </div>
			 <div class="clearfix"></div>
		 </div>
	 </div>
</div>
<!---->
<div class="copywrite">
	 <div class="container">
		 <p>Copyright © 2015 University. All rights reserved | Design by Django girls</p>
	 </div>
</div>
<!---->

</body>
</html>

codepadapp/templates/CodepadAdmin/faculty.html
<!--A Design by W3layouts
Author: W3layout
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE HTML>
<html>
<head>
<title>University a Educational Category Flat Bootstrap Responsive Website Template | About :: w3layouts</title>
    {% load staticfiles %}
<link href="{% static 'css/bootstrap.css' %}" rel='stylesheet' type='text/css' />

    <!-- Custom Theme files -->
<link href="{% static 'css/style.css' %}" rel='stylesheet' type='text/css' />
<!-- Custom Theme files -->
<!--//theme-style-->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="University Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<script src="{% static 'js/jquery.min.js' %}"></script>
 <script src="{% static 'js/bootstrap.js' %}"></script>

    <script type="text/javascript">
        $(document).ready(function(){

            {% if request.session.alert != None %}

                $("#alert_info").html("{{ request.session.alert }}");
                $("#alert_model").modal();

            {% endif %}

        });

    function validate(){

        var emailRegex = /^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/;
        var phoneRegex = /^\(?([0-9]{3})\)?[-.]?([0-9]{3})[-.]?([0-9]{4})$/;

        var valid = true;
        if(!$("#id_email").test(emailRegex)){
            alert("Email invalid");
            valid = false;
        }
        if(!$("#id_phone").test(phoneRegex)){
            alert("Phone no invalid");
            valid= false;
        }

        return false;
    }
    </script>

</head>
<body>
<!-- banner --> 
<div class="banner2">	  
	 <div class="header">
			 <div class="logo">
				 <a href="index.html"><img src="{% static 'images/logo.jpg' %}" alt=""/></a>
			 </div>
			 <div class="top-menu">
				 <span class="menu"></span>
				 <ul class="navig">
					 <li><a href="/Admin/home">Home</a></li>
                     <li><a href="/Admin/lab">Lab</a></li>
					 <li class="active"><a href="/Admin/Faculty">Faculties</a></li>
					 <li><a href="exam">Exam</a></li>
					 <li><a href="contact">Contact</a></li>
					 <li><a href="logout">Logout</a></li>
				 </ul>
			 </div>
			 <!-- script-for-menu -->
		 <script>
				$("span.menu").click(function(){
					$("ul.navig").slideToggle("slow" , function(){
					});
				});
		 </script>
		 <!-- script-for-menu -->
			 <div class="clearfix"></div>
	 </div>	  
</div>
<!---->
<div class="about-sec">
	 <div class="container">
		  <div class="about-head">
			<h2>Labs</h2>
              <div class="col-md-6 col-md-offset-3">
              <form method="post" action="" class="form-horizontal" onsubmit="return validate()">
              {% csrf_token %}

                  <div class="form-group">
                      <label class="col-md-4">Staff ID</label>
                      <div class="col-md-6">
                          {{ form.staffid }}
                      </div>
                  </div>

                  <div class="form-group">
                      <label class="col-md-4">Name</label>
                      <div class="col-md-6">
                          {{ form.name }}
                      </div>
                  </div>

                  <div class="form-group">
                      <label class="col-md-4">Designation</label>
                      <div class="col-md-6">
                          {{ form.designation }}
                      </div>
                  </div>

                  <div class="form-group">
                      <label class="col-md-4">Email</label>
                      <div class="col-md-6">
                          {{ form.email }}
                      </div>
                  </div>

                  <div class="form-group">
                      <label class="col-md-4">Phone</label>
                      <div class="col-md-6">
                          {{ form.phone }}
                      </div>
                  </div>

                  <div class="input-group">
                      <input type="submit" class="btn btn-primary btn-block">
                  </div>
              </form>
                </div>
              <div class="col-md-10 col-md-offset-1">
                   <table class="table">
                      <tr>

                          <th>StaffID</th>
                          <th>Name</th>
                          <th>Designation</th>
                          <th>Email</th>
                          <th>Phone</th>
                      </tr>


                      {% for faculte in faculty %}
                        <tr>
                            <td>{{ faculte.staffid}}</td>
                            <td>{{ faculte.name }}</td>
                            <td>{{ faculte.designation }}</td>
                            <td>{{ faculte.email }}</td>
                            <td>{{ faculte.phone }}</td>

                            <td>
                                <a href="/Admin/editfaculty/{{ faculte.pk }}" class="btn btn-success">Edit</a>
                            </td>
                            <td>
                                <a href="/Admin/deletefaculty/{{ faculte.pk }}" class="btn btn-danger">Delete</a>
                            </td>
                        </tr>
                      {% endfor %}

                  </table>

              </div>
          </div>
	</div>
</div>

<!---->

<!---->
<div class="copywrite">
	 <div class="container">
		 <p>Copyright © 2015 University. All rights reserved | Design by Django girls</p>
	 </div>
</div>
<!---->

        <div class="modal fade" id="alert_model" tabindex="-1" role="dialog">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title">Info</h4>
                    </div>
                    <div class="modal-body">
                        <p id="alert_info"></p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Ok</button>
                    </div>
                </div><!-- /.modal-content -->
            </div><!-- /.modal-dialog -->
        </div><!-- /.modal -->

</body>
</html>